# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Innovators' Practice 2015
tagline:          'The Innovators Practice'
description:      'Hub for <a href="http://bethaltringer.com/es21" target="_blank">ES21</a> course tools, schedule & content. Made by <a href="https://twitter.com/bethaltringer" target="_blank">@bethaltringer</a>.'
url:              http://bethalt.github.io/

author:
  name:           'Beth Altringer'
  url:            https://twitter.com/bethaltringer

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde