# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Innovators' Practice/ Harvard/ Altringer/ 2016
tagline:          'The Innovators Practice'
description:      'Hub for <a href="http://desirabilitylab.com/es21" target="_blank">IP2016</a> course content, schedule & tools.'
url:              http://bethalt.github.io/

author:
  name:           'Beth Altringer'
  url:            https://twitter.com/desirabilitylab

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde